[package]
name = "datacode_encode"
description = "Encodes 1D and 2D data codes with dynamic UI and custom payload parameters."
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
default = []
catch-panics = []

[dependencies]
after-effects = { workspace = true }
utils = { path = "../../crates/utils" }
rxing = "0.8.5"
qrqrpar = "0.1.7"
serde = { version = "1.0.228", features = ["derive"] }


[dev-dependencies]
pipl = { workspace = true }

[build-dependencies]
chrono.workspace = true
pipl.workspace = true

[lints]
workspace = true

