[package]
name = "datacode_encode"
description = "Encodes 1D and 2D data codes from a Liquid template with dynamic UI parameters."
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
default = []
catch-panics = []

[dependencies]
after-effects = { workspace = true }
utils = { path = "../../crates/utils" }
rxing = { version = "0.8.5", default-features = false, features = ["encoding_rs"] }
qrqrpar = "0.1.7"
serde = { version = "1.0.228", features = ["derive"] }
liquid = "0.26.11"

[dev-dependencies]
pipl = { workspace = true }

[build-dependencies]
chrono.workspace = true
pipl.workspace = true

[lints]
workspace = true

