[package]
name = "texture_stroke"
description = "Generates textured strokes from mask and shape paths."
version = "0.3.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = []
catch-panics = []

[dependencies]
after-effects = { workspace = true }
utils = { path = "../../crates/utils" }


[dev-dependencies]
pipl = { workspace = true }

[build-dependencies]
chrono.workspace = true
pipl.workspace = true

[lints]
workspace = true
