[package]
name = "image_relight"
description = "Relights images using color-region, channel-generated, or supplied normal maps."
version = "0.5.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
default = ["gpu_wgpu"]
catch-panics = []
gpu_wgpu = ["dep:wgpu", "dep:bytemuck", "dep:pollster", "dep:futures-intrusive"]

[dependencies]
after-effects = { workspace = true }
utils = { path = "../../crates/utils" }

wgpu = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
futures-intrusive = { workspace = true, optional = true }


[dev-dependencies]
pipl = { workspace = true }

[build-dependencies]
chrono.workspace = true
pipl.workspace = true
winres = "0.1.12"

[lints]
workspace = true
