name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

jobs:
  lint_test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-generate@0.23.7
      - name: License and template checks
        run: python -m unittest discover -s tests -p "test_licensing.py"

      - name: fmt
        run: cargo fmt --all -- --check

      # - name: install jq
      #   run: sudo apt-get update && sudo apt-get install -y jq

      - name: clippy
        shell: bash
        run: |
          cargo clippy --workspace

      - name: test
        shell: bash
        run: |
          cargo test
